services:
  postgres:
    image: postgres:18.1 # Use The Official PostgreSQL Image From Docker Hub
    restart: always # Always Restart The Container If It Stops
    environment:
      POSTGRES_DB: SimpleGameStoreDB # Set The Default Database Name
      POSTGRES_USER: Admin # Set The Default Database User
      POSTGRES_PASSWORD: 1234 # Set The Default Database Password
    volumes:
      - pgdata:/var/lib/postgresql # Persist Data In A Docker Volume

  api:
    build:
      context: . # Build The API Service From The Current Directory
      dockerfile: Dockerfile # Use The Specified Dockerfile
    restart: always # Always Restart The Container If It Stops
    environment:
      ASPNETCORE_ENVIRONMENT: Development # Set The ASP.NET Core Environment To Production
      ASPNETCORE_URLS: "http://+:80" # Configure The API To Listen On Port 80
      ConnectionStrings__DefaultConnection: Host=postgres;Database=SimpleGameStoreDB;Username=Admin;Password=1234 # Database Connection String
    depends_on:
      - postgres # Ensure The API Service Starts After The PostgreSQL Service
    ports:
      - "5000:80" # Map API Port To The Host



volumes:
  pgdata: # Define A Named Volume For PostgreSQL Data Persistence