services:
  postgres:
    image: postgres:18.1 # Use The Official PostgreSQL Image From Docker Hub
    restart: always # Always Restart The Container If It Stops
    environment:
      POSTGRES_DB: SimpleGameStoreDB # Set The Default Database Name
      POSTGRES_USER: Admin # Set The Default Database User
      POSTGRES_PASSWORD: 1234 # Set The Default Database Password
    volumes:
      - pgdata:/var/lib/postgresql # Persist Data In A Docker Volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Admin -d SimpleGameStoreDB"] # Check If PostgreSQL Is Ready To Accept Connections
      interval: 10s # Check Every 10 Seconds
      retries: 5 # Retry Up To 5 Times Before Marking As Unhealthy
      timeout: 5s # Timeout After 5 Seconds

  api:
    image: argul0/simple-game-store:simple-game-store-web-api-1.1.1 # Use The Published Docker Image From Docker Hub For Current Version
    restart: always # Always Restart The Container If It Stops
    environment:
      ASPNETCORE_ENVIRONMENT: Production # Set The ASP.NET Core Environment To Production
      ASPNETCORE_URLS: "http://+:80" # Configure The API To Listen On Port 80
      ConnectionStrings__DefaultConnection: Host=postgres;Database=SimpleGameStoreDB;Username=Admin;Password=1234 # Database Connection String
    depends_on:
      postgres:
          condition: service_healthy # Ensure The API Starts Only After PostgreSQL Is Healthy
    ports:
      - "5000:80" # Map API Port To The Host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"] # Check If The API Is Healthy By Hitting The /health Endpoint
      interval: 10s # Check Every 10 Seconds
      retries: 5 # Retry Up To 5 Times Before Marking As Unhealthy
      timeout: 3s # Timeout After 3 Seconds



volumes:
  pgdata: # Define A Named Volume For PostgreSQL Data Persistence